---
# from https://github.com/ansible/awx/blob/devel/
# requirements/collections_requirements.yml
collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws  # PR 125 is in 1.1.0
  - name: theforeman.foreman  # has requirements.txt (which -r to another file)
  - name: google.cloud  # has requirements.txt, mainly for google-auth
  - name: openstack.cloud
  - name: community.vmware  # has requirements.txt, but may add pyvcloud
  - name: ovirt.ovirt
  - name: community.kubernetes
  - name: ansible.posix
